import React from 'react';

interface EssayDisplayProps {
  text: string;
  onReset: () => void;
}

const EssayDisplay: React.FC<EssayDisplayProps> = ({ text, onReset }) => {
  const handleCopy = () => {
    navigator.clipboard.writeText(text);
    alert('Text copied to clipboard!');
  };

  return (
    <div className="w-full max-w-2xl mx-auto mt-8 bg-white rounded-xl shadow-lg border border-gray-100 overflow-hidden animate-fade-in-up">
      <div className="bg-teal-600 px-6 py-4 flex justify-between items-center">
        <h2 className="text-white font-semibold text-lg">Essay Draft (Burmese)</h2>
        <div className="flex space-x-2">
           <button 
            onClick={handleCopy}
            className="text-white/80 hover:text-white hover:bg-teal-700 px-3 py-1 rounded-md text-sm transition-colors"
          >
            Copy
          </button>
          <button 
            onClick={onReset}
            className="text-white/80 hover:text-white hover:bg-teal-700 px-3 py-1 rounded-md text-sm transition-colors"
          >
            New
          </button>
        </div>
      </div>
      <div className="p-6">
        <textarea
          readOnly
          value={text}
          className="w-full h-64 p-4 text-lg leading-relaxed text-gray-800 burmese-text border-0 focus:ring-0 resize-none bg-gray-50 rounded-lg"
          style={{ lineHeight: '2' }}
        />
        <div className="mt-4 text-xs text-gray-400 text-center">
          Generated by Gemini 2.5 Flash
        </div>
      </div>
    </div>
  );
};

export default EssayDisplay;
